import type { Technology } from '@/types/database';

const react: Technology = {
  id: '1',
  name: 'React',
  slug: 'react',
  category: 'frontend-framework',
  description: 'A JavaScript library for building user interfaces with a component-based architecture and virtual DOM.',
  logo_url: null,
  website_url: 'https://react.dev',
  github_url: 'https://github.com/facebook/react',
  npm_package: 'react',
  github_stars: 228000,
  npm_weekly_downloads: 25000000,
  pros: ['Massive ecosystem', 'Strong job market', 'Flexible architecture', 'React Native for mobile'],
  cons: ['JSX learning curve', 'Frequent ecosystem changes', 'Boilerplate for state management'],
  best_for: ['Large-scale SPAs', 'Cross-platform development', 'Projects needing many third-party libraries'],
  learning_curve: 'intermediate',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2013', maintained_by: 'Meta' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const vuejs: Technology = {
  id: '2',
  name: 'Vue.js',
  slug: 'vuejs',
  category: 'frontend-framework',
  description: 'A progressive JavaScript framework for building UIs, designed to be incrementally adoptable.',
  logo_url: null,
  website_url: 'https://vuejs.org',
  github_url: 'https://github.com/vuejs/core',
  npm_package: 'vue',
  github_stars: 208000,
  npm_weekly_downloads: 4500000,
  pros: ['Gentle learning curve', 'Excellent documentation', 'Built-in state management', 'Small bundle size'],
  cons: ['Smaller ecosystem than React', 'Fewer job postings', 'Less corporate backing'],
  best_for: ['Rapid prototyping', 'Small to medium apps', 'Teams transitioning from jQuery'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2014', maintained_by: 'Evan You & community' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const nextjs: Technology = {
  id: '3',
  name: 'Next.js',
  slug: 'nextjs',
  category: 'fullstack-framework',
  description: 'A React framework for production with hybrid static/server rendering, route handlers, and built-in optimizations.',
  logo_url: null,
  website_url: 'https://nextjs.org',
  github_url: 'https://github.com/vercel/next.js',
  npm_package: 'next',
  github_stars: 130000,
  npm_weekly_downloads: 7000000,
  pros: ['Server-side rendering', 'File-based routing', 'API routes', 'Excellent DX', 'Vercel integration'],
  cons: ['Vercel vendor lock-in concerns', 'Complex deployment without Vercel', 'Opinionated structure'],
  best_for: ['SEO-critical apps', 'Full-stack React projects', 'Content-heavy sites'],
  learning_curve: 'intermediate',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2016', maintained_by: 'Vercel' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const svelte: Technology = {
  id: '4',
  name: 'Svelte',
  slug: 'svelte',
  category: 'frontend-framework',
  description: 'A compiler-based framework that shifts work from runtime to build time, producing highly optimized vanilla JS.',
  logo_url: null,
  website_url: 'https://svelte.dev',
  github_url: 'https://github.com/sveltejs/svelte',
  npm_package: 'svelte',
  github_stars: 80000,
  npm_weekly_downloads: 1200000,
  pros: ['No virtual DOM overhead', 'Minimal boilerplate', 'Small bundle sizes', 'Built-in animations'],
  cons: ['Smaller ecosystem', 'Fewer jobs', 'Less mature tooling', 'Smaller community'],
  best_for: ['Performance-critical apps', 'Small to medium projects', 'Developers who prefer less abstraction'],
  learning_curve: 'beginner',
  community_size: 'medium',
  maturity: 'growing',
  metadata: { first_release: '2016', maintained_by: 'Rich Harris & community' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const expressjs: Technology = {
  id: '5',
  name: 'Express.js',
  slug: 'expressjs',
  category: 'backend-framework',
  description: 'A minimal and flexible Node.js web application framework providing robust features for web and mobile apps.',
  logo_url: null,
  website_url: 'https://expressjs.com',
  github_url: 'https://github.com/expressjs/express',
  npm_package: 'express',
  github_stars: 66000,
  npm_weekly_downloads: 35000000,
  pros: ['Extremely mature', 'Massive middleware ecosystem', 'Simple and flexible', 'Well-documented'],
  cons: ['Minimal out-of-the-box', 'No built-in TypeScript support', 'Callback-heavy patterns'],
  best_for: ['REST APIs', 'Microservices', 'Backend for any frontend framework'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2010', maintained_by: 'OpenJS Foundation' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const fastapi: Technology = {
  id: '6',
  name: 'FastAPI',
  slug: 'fastapi',
  category: 'backend-framework',
  description: 'A modern, fast Python web framework for building APIs with automatic OpenAPI docs and type validation.',
  logo_url: null,
  website_url: 'https://fastapi.tiangolo.com',
  github_url: 'https://github.com/tiangolo/fastapi',
  npm_package: null,
  github_stars: 80000,
  npm_weekly_downloads: null,
  pros: ['Auto-generated API docs', 'Type validation with Pydantic', 'Async support', 'Very fast'],
  cons: ['Python-only', 'Younger ecosystem', 'Fewer deployment options than Node'],
  best_for: ['Python APIs', 'ML model serving', 'Data-heavy backends'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'growing',
  metadata: { first_release: '2018', maintained_by: 'Sebastián Ramírez' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const postgresql: Technology = {
  id: '7',
  name: 'PostgreSQL',
  slug: 'postgresql',
  category: 'database',
  description: 'A powerful, open-source relational database with extensive SQL compliance and advanced features.',
  logo_url: null,
  website_url: 'https://www.postgresql.org',
  github_url: 'https://github.com/postgres/postgres',
  npm_package: null,
  github_stars: 17000,
  npm_weekly_downloads: null,
  pros: ['ACID compliant', 'Advanced features (JSONB, full-text search)', 'Extensible', 'Strong data integrity'],
  cons: ['Complex configuration', 'Higher memory usage', 'Steeper learning curve than SQLite'],
  best_for: ['Production applications', 'Complex queries', 'Data integrity critical systems'],
  learning_curve: 'intermediate',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '1996', maintained_by: 'PostgreSQL Global Development Group' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const mongodb: Technology = {
  id: '8',
  name: 'MongoDB',
  slug: 'mongodb',
  category: 'database',
  description: 'A document-oriented NoSQL database designed for scalability and developer productivity.',
  logo_url: null,
  website_url: 'https://www.mongodb.com',
  github_url: 'https://github.com/mongodb/mongo',
  npm_package: 'mongodb',
  github_stars: 27000,
  npm_weekly_downloads: 2500000,
  pros: ['Flexible schema', 'Horizontal scaling', 'JSON-like documents', 'Great for prototyping'],
  cons: ['No ACID transactions (historically)', 'Data duplication', 'Complex aggregation pipeline'],
  best_for: ['Rapid prototyping', 'Content management', 'Real-time analytics', 'IoT data'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2009', maintained_by: 'MongoDB Inc.' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const tailwindcss: Technology = {
  id: '9',
  name: 'Tailwind CSS',
  slug: 'tailwindcss',
  category: 'css-framework',
  description: 'A utility-first CSS framework for rapidly building custom user interfaces without leaving your HTML.',
  logo_url: null,
  website_url: 'https://tailwindcss.com',
  github_url: 'https://github.com/tailwindlabs/tailwindcss',
  npm_package: 'tailwindcss',
  github_stars: 85000,
  npm_weekly_downloads: 12000000,
  pros: ['Rapid development', 'Consistent design system', 'Small production bundles', 'Great DX'],
  cons: ['Verbose class names', 'Learning utility names', 'HTML can look cluttered'],
  best_for: ['Custom designs', 'Component libraries', 'Projects with design systems'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2017', maintained_by: 'Tailwind Labs' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const supabase: Technology = {
  id: '10',
  name: 'Supabase',
  slug: 'supabase',
  category: 'backend-as-a-service',
  description: 'An open-source Firebase alternative providing auth, database (Postgres), storage, and real-time subscriptions.',
  logo_url: null,
  website_url: 'https://supabase.com',
  github_url: 'https://github.com/supabase/supabase',
  npm_package: '@supabase/supabase-js',
  github_stars: 75000,
  npm_weekly_downloads: 800000,
  pros: ['Built on PostgreSQL', 'Row Level Security', 'Real-time subscriptions', 'Auth built-in', 'Open source'],
  cons: ['Younger than Firebase', 'Fewer integrations', 'Limited edge functions'],
  best_for: ['Full-stack apps needing auth + DB', 'Real-time features', 'PostgreSQL fans'],
  learning_curve: 'beginner',
  community_size: 'medium',
  maturity: 'growing',
  metadata: { first_release: '2020', maintained_by: 'Supabase Inc.' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const typescript: Technology = {
  id: '11',
  name: 'TypeScript',
  slug: 'typescript',
  category: 'language',
  description: 'A typed superset of JavaScript that compiles to plain JavaScript, adding optional static typing.',
  logo_url: null,
  website_url: 'https://www.typescriptlang.org',
  github_url: 'https://github.com/microsoft/TypeScript',
  npm_package: 'typescript',
  github_stars: 102000,
  npm_weekly_downloads: 50000000,
  pros: ['Type safety', 'Better IDE support', 'Catches errors early', 'Great for large codebases'],
  cons: ['Compilation step', 'Learning curve for types', 'Configuration complexity'],
  best_for: ['Large applications', 'Team projects', 'Library development'],
  learning_curve: 'intermediate',
  community_size: 'large',
  maturity: 'mature',
  metadata: { first_release: '2012', maintained_by: 'Microsoft' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

const prisma: Technology = {
  id: '12',
  name: 'Prisma',
  slug: 'prisma',
  category: 'orm',
  description: 'A next-generation Node.js and TypeScript ORM with a declarative schema and type-safe database client.',
  logo_url: null,
  website_url: 'https://www.prisma.io',
  github_url: 'https://github.com/prisma/prisma',
  npm_package: 'prisma',
  github_stars: 40000,
  npm_weekly_downloads: 3000000,
  pros: ['Type-safe queries', 'Auto-generated client', 'Schema migrations', 'Great DX'],
  cons: ['Performance overhead', 'Limited raw SQL flexibility', 'Large dependency'],
  best_for: ['TypeScript projects', 'Rapid development', 'Teams wanting type-safe DB access'],
  learning_curve: 'beginner',
  community_size: 'large',
  maturity: 'growing',
  metadata: { first_release: '2019', maintained_by: 'Prisma' },
  created_at: '2024-01-01T00:00:00Z',
  updated_at: '2024-01-01T00:00:00Z',
};

export const FIXTURE_TECHNOLOGIES: Technology[] = [
  react,
  vuejs,
  nextjs,
  svelte,
  expressjs,
  fastapi,
  postgresql,
  mongodb,
  tailwindcss,
  supabase,
  typescript,
  prisma,
];

export const FIXTURE_TECHNOLOGIES_BY_SLUG: Record<string, Technology> = Object.fromEntries(
  FIXTURE_TECHNOLOGIES.map((t) => [t.slug, t])
);
