import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const technologies = [
  {
    name: 'React',
    slug: 'react',
    category: 'frontend-framework',
    description: 'A JavaScript library for building user interfaces with a component-based architecture and virtual DOM.',
    website_url: 'https://react.dev',
    github_url: 'https://github.com/facebook/react',
    npm_package: 'react',
    github_stars: 228000,
    npm_weekly_downloads: 25000000,
    pros: ['Massive ecosystem', 'Strong job market', 'Flexible architecture', 'React Native for mobile'],
    cons: ['JSX learning curve', 'Frequent ecosystem changes', 'Boilerplate for state management'],
    best_for: ['Large-scale SPAs', 'Cross-platform development', 'Projects needing many third-party libraries'],
    learning_curve: 'intermediate' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2013', maintained_by: 'Meta' },
  },
  {
    name: 'Vue.js',
    slug: 'vuejs',
    category: 'frontend-framework',
    description: 'A progressive JavaScript framework for building UIs, designed to be incrementally adoptable.',
    website_url: 'https://vuejs.org',
    github_url: 'https://github.com/vuejs/core',
    npm_package: 'vue',
    github_stars: 208000,
    npm_weekly_downloads: 4500000,
    pros: ['Gentle learning curve', 'Excellent documentation', 'Built-in state management', 'Small bundle size'],
    cons: ['Smaller ecosystem than React', 'Fewer job postings', 'Less corporate backing'],
    best_for: ['Rapid prototyping', 'Small to medium apps', 'Teams transitioning from jQuery'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2014', maintained_by: 'Evan You & community' },
  },
  {
    name: 'Next.js',
    slug: 'nextjs',
    category: 'fullstack-framework',
    description: 'A React framework for production with hybrid static/server rendering, route handlers, and built-in optimizations.',
    website_url: 'https://nextjs.org',
    github_url: 'https://github.com/vercel/next.js',
    npm_package: 'next',
    github_stars: 130000,
    npm_weekly_downloads: 7000000,
    pros: ['Server-side rendering', 'File-based routing', 'API routes', 'Excellent DX', 'Vercel integration'],
    cons: ['Vercel vendor lock-in concerns', 'Complex deployment without Vercel', 'Opinionated structure'],
    best_for: ['SEO-critical apps', 'Full-stack React projects', 'Content-heavy sites'],
    learning_curve: 'intermediate' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2016', maintained_by: 'Vercel' },
  },
  {
    name: 'Svelte',
    slug: 'svelte',
    category: 'frontend-framework',
    description: 'A compiler-based framework that shifts work from runtime to build time, producing highly optimized vanilla JS.',
    website_url: 'https://svelte.dev',
    github_url: 'https://github.com/sveltejs/svelte',
    npm_package: 'svelte',
    github_stars: 80000,
    npm_weekly_downloads: 1200000,
    pros: ['No virtual DOM overhead', 'Minimal boilerplate', 'Small bundle sizes', 'Built-in animations'],
    cons: ['Smaller ecosystem', 'Fewer jobs', 'Less mature tooling', 'Smaller community'],
    best_for: ['Performance-critical apps', 'Small to medium projects', 'Developers who prefer less abstraction'],
    learning_curve: 'beginner' as const,
    community_size: 'medium' as const,
    maturity: 'growing' as const,
    metadata: { first_release: '2016', maintained_by: 'Rich Harris & community' },
  },
  {
    name: 'Express.js',
    slug: 'expressjs',
    category: 'backend-framework',
    description: 'A minimal and flexible Node.js web application framework providing robust features for web and mobile apps.',
    website_url: 'https://expressjs.com',
    github_url: 'https://github.com/expressjs/express',
    npm_package: 'express',
    github_stars: 66000,
    npm_weekly_downloads: 35000000,
    pros: ['Extremely mature', 'Massive middleware ecosystem', 'Simple and flexible', 'Well-documented'],
    cons: ['Minimal out-of-the-box', 'No built-in TypeScript support', 'Callback-heavy patterns'],
    best_for: ['REST APIs', 'Microservices', 'Backend for any frontend framework'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2010', maintained_by: 'OpenJS Foundation' },
  },
  {
    name: 'FastAPI',
    slug: 'fastapi',
    category: 'backend-framework',
    description: 'A modern, fast Python web framework for building APIs with automatic OpenAPI docs and type validation.',
    website_url: 'https://fastapi.tiangolo.com',
    github_url: 'https://github.com/tiangolo/fastapi',
    npm_package: null,
    github_stars: 80000,
    npm_weekly_downloads: null,
    pros: ['Auto-generated API docs', 'Type validation with Pydantic', 'Async support', 'Very fast'],
    cons: ['Python-only', 'Younger ecosystem', 'Fewer deployment options than Node'],
    best_for: ['Python APIs', 'ML model serving', 'Data-heavy backends'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'growing' as const,
    metadata: { first_release: '2018', maintained_by: 'Sebastián Ramírez' },
  },
  {
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'database',
    description: 'A powerful, open-source relational database with extensive SQL compliance and advanced features.',
    website_url: 'https://www.postgresql.org',
    github_url: 'https://github.com/postgres/postgres',
    npm_package: null,
    github_stars: 17000,
    npm_weekly_downloads: null,
    pros: ['ACID compliant', 'Advanced features (JSONB, full-text search)', 'Extensible', 'Strong data integrity'],
    cons: ['Complex configuration', 'Higher memory usage', 'Steeper learning curve than SQLite'],
    best_for: ['Production applications', 'Complex queries', 'Data integrity critical systems'],
    learning_curve: 'intermediate' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '1996', maintained_by: 'PostgreSQL Global Development Group' },
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    category: 'database',
    description: 'A document-oriented NoSQL database designed for scalability and developer productivity.',
    website_url: 'https://www.mongodb.com',
    github_url: 'https://github.com/mongodb/mongo',
    npm_package: 'mongodb',
    github_stars: 27000,
    npm_weekly_downloads: 2500000,
    pros: ['Flexible schema', 'Horizontal scaling', 'JSON-like documents', 'Great for prototyping'],
    cons: ['No ACID transactions (historically)', 'Data duplication', 'Complex aggregation pipeline'],
    best_for: ['Rapid prototyping', 'Content management', 'Real-time analytics', 'IoT data'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2009', maintained_by: 'MongoDB Inc.' },
  },
  {
    name: 'Tailwind CSS',
    slug: 'tailwindcss',
    category: 'css-framework',
    description: 'A utility-first CSS framework for rapidly building custom user interfaces without leaving your HTML.',
    website_url: 'https://tailwindcss.com',
    github_url: 'https://github.com/tailwindlabs/tailwindcss',
    npm_package: 'tailwindcss',
    github_stars: 85000,
    npm_weekly_downloads: 12000000,
    pros: ['Rapid development', 'Consistent design system', 'Small production bundles', 'Great DX'],
    cons: ['Verbose class names', 'Learning utility names', 'HTML can look cluttered'],
    best_for: ['Custom designs', 'Component libraries', 'Projects with design systems'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2017', maintained_by: 'Tailwind Labs' },
  },
  {
    name: 'Supabase',
    slug: 'supabase',
    category: 'backend-as-a-service',
    description: 'An open-source Firebase alternative providing auth, database (Postgres), storage, and real-time subscriptions.',
    website_url: 'https://supabase.com',
    github_url: 'https://github.com/supabase/supabase',
    npm_package: '@supabase/supabase-js',
    github_stars: 75000,
    npm_weekly_downloads: 800000,
    pros: ['Built on PostgreSQL', 'Row Level Security', 'Real-time subscriptions', 'Auth built-in', 'Open source'],
    cons: ['Younger than Firebase', 'Fewer integrations', 'Limited edge functions'],
    best_for: ['Full-stack apps needing auth + DB', 'Real-time features', 'PostgreSQL fans'],
    learning_curve: 'beginner' as const,
    community_size: 'medium' as const,
    maturity: 'growing' as const,
    metadata: { first_release: '2020', maintained_by: 'Supabase Inc.' },
  },
  {
    name: 'TypeScript',
    slug: 'typescript',
    category: 'language',
    description: 'A typed superset of JavaScript that compiles to plain JavaScript, adding optional static typing.',
    website_url: 'https://www.typescriptlang.org',
    github_url: 'https://github.com/microsoft/TypeScript',
    npm_package: 'typescript',
    github_stars: 102000,
    npm_weekly_downloads: 50000000,
    pros: ['Type safety', 'Better IDE support', 'Catches errors early', 'Great for large codebases'],
    cons: ['Compilation step', 'Learning curve for types', 'Configuration complexity'],
    best_for: ['Large applications', 'Team projects', 'Library development'],
    learning_curve: 'intermediate' as const,
    community_size: 'large' as const,
    maturity: 'mature' as const,
    metadata: { first_release: '2012', maintained_by: 'Microsoft' },
  },
  {
    name: 'Prisma',
    slug: 'prisma',
    category: 'orm',
    description: 'A next-generation Node.js and TypeScript ORM with a declarative schema and type-safe database client.',
    website_url: 'https://www.prisma.io',
    github_url: 'https://github.com/prisma/prisma',
    npm_package: 'prisma',
    github_stars: 40000,
    npm_weekly_downloads: 3000000,
    pros: ['Type-safe queries', 'Auto-generated client', 'Schema migrations', 'Great DX'],
    cons: ['Performance overhead', 'Limited raw SQL flexibility', 'Large dependency'],
    best_for: ['TypeScript projects', 'Rapid development', 'Teams wanting type-safe DB access'],
    learning_curve: 'beginner' as const,
    community_size: 'large' as const,
    maturity: 'growing' as const,
    metadata: { first_release: '2019', maintained_by: 'Prisma' },
  },
];

async function seed() {
  console.log('Seeding technologies...');

  const { data, error } = await supabase
    .from('technologies')
    .upsert(technologies, { onConflict: 'slug' })
    .select();

  if (error) {
    console.error('Error seeding:', error);
    process.exit(1);
  }

  console.log(`Seeded ${data.length} technologies successfully.`);
}

seed();
